<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mindstorms" nsURI="http://www.obeo.fr/dsl/mindstorms/1.0.0"
    nsPrefix="mindstorms">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Main">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BlockContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Procedure" eSuperTypes="#//Instruction #//BlockContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arbitrator" eSuperTypes="#//Instruction #//ConditionContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviors" upperBound="-1"
        eType="#//Behavior" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reuse" upperBound="-1"
        eType="#//Behavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" eSuperTypes="#//NamedElement #//BlockContainer #//ConditionContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReuseInstruction" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reuse" eType="#//Instruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" eSuperTypes="#//Block"/>
  <eClassifiers xsi:type="ecore:EClass" name="Flow" abstract="true" eSuperTypes="#//Block #//BlockContainer #//ConditionContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" abstract="true" eSuperTypes="#//NamedElement #//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//Flow"/>
  <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="#//Flow"/>
  <eClassifiers xsi:type="ecore:EClass" name="GoForward" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infinite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoBackward" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infinite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rotate" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degrees" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="random" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoTo" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnToBase" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Grab" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Release" eSuperTypes="#//Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ms" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AvoidObstacle" eSuperTypes="#//Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnBottleToBase" eSuperTypes="#//Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExploreForward" eSuperTypes="#//Behavior"/>
  <eClassifiers xsi:type="ecore:EClass" name="TouchSensor" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPressed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UltrasonicSensor" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//OperatorKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorSensor" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"
        defaultValueLiteral="NONE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="RED"/>
    <eLiterals name="GREEN" value="1"/>
    <eLiterals name="BLUE" value="2"/>
    <eLiterals name="YELLOW" value="3"/>
    <eLiterals name="MAGENTA" value="4"/>
    <eLiterals name="ORANGE" value="5"/>
    <eLiterals name="WHITE" value="6"/>
    <eLiterals name="BLACK" value="7"/>
    <eLiterals name="PINK" value="8"/>
    <eLiterals name="GRAY" value="9"/>
    <eLiterals name="LIGHT_GRAY" value="10"/>
    <eLiterals name="DARK_GRAY" value="11"/>
    <eLiterals name="CYAN" value="12"/>
    <eLiterals name="BROWN" value="13"/>
    <eLiterals name="NONE" value="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorKind">
    <eLiterals name="equal"/>
    <eLiterals name="notEqual"/>
    <eLiterals name="upperOrEqual"/>
    <eLiterals name="lowerOrEqual"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoToEnemy" eSuperTypes="#//Action"/>
</ecore:EPackage>
